### ISSUE TITLE
No implicit conversion of IO into String

### ISSUE THREAD

**Issue by jneen** [jneen/rouge#487]
It seems like #417 was a little overzealous - the FileReader class had been introduced to distinguish between stdin (or `'-'`) and file names. When using `rougify` to highlight stdin, we now try to call `File.read($stdin, encoding: 'utf-8')`, which throws an error.

**Comment by jneen** [comment]
@japj could you take a look at this please?

**Comment by jneen** [comment]
(when you get a chance - if you don't have the time I'm happy to fix it of course)

**Comment by japj** [comment]
I'll have a look later today, not sure exactly atm how to have a reproduceable test for this to prevent regression in the future. My ruby is fairly rusty

**Comment by japj** [comment]
Ok, I am a bit lost on how to solve this issue due to not programming in ruby for a looong time and the unknowns of the IO subsystem.

Should https://github.com/jneen/rouge/blob/master/lib/rouge/cli.rb#L16 return a different kind of object (this is what I am assuming should happen as the 'correct' fix, but I'm not sure what object it should be exactly for L26 to also still work correctly).

Or should https://github.com/jneen/rouge/blob/master/lib/rouge/cli.rb#L26 contain the old code in case of stdin, but then there is duplication on the case input/when part?

**Comment by jneen** [comment]
I think you can embed the encoding into the File object with `File.new(fname, 'r:utf-8')` or similar

**Comment by japj** [comment]
I guess this can be closed then?

**Comment by jneen** [comment]
Yep!
