### ISSUE TITLE
Syntax highlighting spins indefinitely with SQL text

### ISSUE THREAD

**Issue by stanhu** [jneen/rouge#525]
I think this is similar to https://gitlab.com/gitlab-org/gitlab-ce/issues/17327. I added this comment in GitLab and noticed everything stopped rendering:

```
lib/banzai/filter/syntax_highlight_filter.rb:28:in `highlight_node'
  lib/gitlab/metrics/instrumentation.rb:152:in `block in highlight_node'
  lib/gitlab/metrics/method_call.rb:23:in `measure'
  lib/gitlab/metrics/transaction.rb:71:in `measure_method'
```

Attached is the raw text:

[bad_note.txt](https://github.com/jneen/rouge/files/410135/bad_note.txt)

**Comment by jneen** [comment]
Interestingly, the SQL lexer is not involved here, since it's wrapped in a JSON string. I believe I've resolved this with the last three commits on master here - could you confirm that?

I think there were a couple of things going on:

* A bad regex `/"(\\.|[^"])*"/` was backtracking at every backslash since it could match either the first or the second option. Could be fixed by using `[^\\"]` or a non-greedy `*?` splat instead, but
* The JSON lexer was just overall too complicated and tried to find nesting errors and the like (the given text was just `"key": "value"` which we didn't support).

To fix this, I stripped most of the functionality from the JSON lexer and switched to manually walking through strings, which has the added advantage of being able to highlight backslash escapes. (15d2469ad01575573370f531eb6b33df509cfd58)

Finally, there was a triple backtick in one of the strings which was causing markdown to get confused about where the code block ended, so I now require a newline before the closing delimiter. (cc54a87c489856488aae8100dc8a01d66a8cc0c3)

**Comment by stanhu** [comment]
@jneen Great work!

**Comment by stanhu** [comment]
@jneen I just had a chance to test out master@8439fd6 with the note in question. It passes with flying colors now! Thank you. Can you release a new version soon?
