### ISSUE TITLE
Makefile highlighting always incorrect (even for trivial Makefiles)

### ISSUE THREAD

**Issue by mnhrdt** [jneen/rouge#694]
I updated from a very old version, and now all the makefile highlights are completely wrong.  Is current makefile support still useful?

See, e.g.:  http://rouge.jneen.net/pastes/E96e

I would not expect reverse bright red in one rule but not in the other

(edit: changed the example to a simpler one)

**Comment by dblessing** [comment]
This error only occurs if there is no newline at the end. I couldn't reproduce it initially because my editor adds newlines at the end on save. The rule that 'causes' this is at https://github.com/jneen/rouge/blob/master/lib/rouge/lexers/make.rb#L99. Basically, it looks for a newline as a 'stop'. 

The question is - is this a bug, or intended behavior? The only thing I can think of is to change the rule from:

```make
stop = /\$\(|\(|\)|\n|\\/
```

to:

```make
stop = /\$\(|\(|\)|\n|\\|$/
```

which matches on end of line as a last resort. In a quick test, it doesn't break the sample. 

Any thoughts @jneen and @gfx?

**Comment by jneen** [comment]
Yep - rouge should behave correctly even when there isn't a newline at the end - often people will `.strip` a string and then highlight it. So @dblessing I think your fix is correct - I might even remove the `\n` from the regex and see how it performs.

We've fixed a number of similar bugs, by the way, mostly to do with comments searching for `#.*?\n` for example

**Comment by mnhrdt** [comment]
Great! This effectively solves the problem.

FYI, the context where this error happens is within liquid markdown on jekyll.  Even if you add a white line before the "endhighlight" tag, it is stripped out by the markdown engine, and rouge effectively receives a string without an endline.  I do not know if this is considered a bug in jekyll also.

Thank you very much for your answers.
