### ISSUE TITLE
⚠️ Maintenance of this project? ⚠️

### ISSUE THREAD

**Issue by miparnisari** [jneen/rouge#890]
I've talked to the owner of this project. She is a full-time student and doesn't have time to maintain this repository.

I've also talked to my org in look for project sponsoring. Still waiting on a response.

There are currently 63 pull requests waiting to be merged.

Is there anything we can do to keep this project going? I'm not sure what is the best course of action here.

**Comment by jolkdarr** [comment]
Hi

Thanks for information.
Does anyone wish to acquire the ownership of the project?

**Comment by jolkdarr** [comment]
OK. Is reviewing also required for PRs related to new languages or formats?

**Comment by gfx** [comment]
Well, I'll back in a few weeks. In fact, I have some tasks to care my child, born in Sep. 2017 👶 .

**Comment by jneen** [comment]
@dblessing my understanding was that GitLab was continuing to sponsor your work on this project, though...

**Comment by jneen** [comment]
@gfx oh, congratulations! your child definitely comes first <3

**Comment by jneen** [comment]
I should also note that GitLab declined to sponsor a few weeks of my time last month, citing that they were not able to upgrade to 3.x because of gollum's dependency on 2.x.

**Comment by jneen** [comment]
cc @stanhu for details there, maybe there's something they could do to get unblocked.

**Comment by dblessing** [comment]
@jneen I’m mostly on my own time. I can use work time, too, but lately
other things have been too crazy.

I reviewed and merged a bunch of stuff today. I’ll try to set aside a few
hours per week at least.

@jneen @gfx Will one of you please add me to RubyGems (dblessing). And @gfx
maybe when you get back, walk me through your release process. Congrats on
the birth of your child. Take care!

**Comment by miparnisari** [comment]
One thing I forgot to ask was whether you can switch the donation provider? Or add another one. https://cash.me doesn't work in Canada.

**Comment by mathewmariani** [comment]
@jneen @gfx @dblessing : I wouldn't mind spending some time maintaining the project and doing PR reviews of the languages people are trying to add.

**Comment by miparnisari** [comment]
@jneen @gfx @dblessing @mathewmariani I can help too, i've written two lexers so at least i'm somewhat familiar with the syntax.

**Comment by jneen** [comment]
@dblessing I noticed you mention that you are working on Rouge in your spare time. Are you no longer employed by gitlab? The agreement when I left was that you would be able to work on Rouge on paid company time, since a *very* large portion of the maintenance burden comes from gitlab - as far as users are concerned, any rouge bug is a gitlab bug. @stanhu do you have any insight into this?

**Comment by miparnisari** [comment]
Er.. any updates on this? :(

**Comment by stanhu** [comment]
> The agreement when I left was that you would be able to work on Rouge on paid company time, since a very large portion of the maintenance burden comes from gitlab - as far as users are concerned

@jneen Hope school is going well! Apologies, I was not aware of any such agreement, but let me introduce you to people who might be able to have that discussion about Rouge going forward.

**Comment by dblessing** [comment]
@mathewmariani Happy to have you help out if you're interested. Probably the best way to get started is for you to start going through issues/PRs and do some initial reviews. Ping me and I can do final review. I am also happy to have a few pairing sessions with you. We'll start with that and if it goes well I'll talk with @jneen about adding you as a maintainer. 

@miparnisari I've spent quite a bit of time in the last month of so reviewing PRs. See https://github.com/jneen/rouge/blob/master/CHANGELOG.md for the changes going into the next release. I plan to cut a new version tonight or tomorrow. I hope to keep this pace from here. I haven't been as active in the past couple of weeks because of some personal things. 

For all intents and purposes I think we can close this for now. If anyone else is interested in helping out with reviews/triage, ping me and we can work together.
